#ifndef MODULECONFIG_HPP
#define MODULECONFIG_HPP

#define USE_SERIAL
#define SERIAL_MENU_THREAD_TIME_INTERVAL_MS 100

#define VOBULATOR_THREAD_TIME_INTERVAL_MS 10

#define VOBULATOR_BY_DC_THREAD_TIME_INTERVAL_MS 50

#endif