#ifndef MODULECONFIG_HPP
#define MODULECONFIG_HPP

#ifdef USE_ESP32
#define ESP_WATCHDOG_TIMEOUT_SEK 3U
#define VOBULATOR_BY_DC_THREAD_TIME_INTERVAL_MS 50U
#endif

#define USE_SERIAL
#ifdef USE_SERIAL
#define SERIAL_MENU_THREAD_TIME_INTERVAL_MS 100U
#endif

#define VOBULATOR_THREAD_TIME_INTERVAL_MS 10U

#endif